[package]
name = "interprust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

opencv = "0.60"
tokio-tungstenite = { version = "*", features = ["native-tls"]}

[features]

default = ["native-tls"]
native-tls = []
