BOARD_TAG = esp8266
ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = 			#path to arduino-makefile (/usr/lib?)
AVR_TOOLS_DIR = /usr
AVRDUDE = /usr/bin/avrdude
MONITOR_PORT = /dev/ttyUSB0
include /usr/share/arduino/Arduino.mk
